services:
  - type: web
    name: whatsapp-session-pairing-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
      - key: SESSION_FILE
        value: ./session_data/creds.json
